### ISSUE TITLE
No write permission error

### ISSUE THREAD

**Issue by pot-code** [Dankr4d/BF2142Unlocker#61]
**OS**: win10 home edition
**Installation version**: BF2142Unlocker_v0.9.5_win
**Game version**: fresh install, v1.51
**How**: run unlock app and click Singleplayer, the same for the Host button

**Screenshot**:

![no_write_access](https://user-images.githubusercontent.com/17687881/106465148-89a3f480-64d4-11eb-893e-79106add637f.jpg)

**About the privilege**:

I have checked all of the privileges, for the path `C:\Program Files (x86)\Electronic Arts`

**Comment by pot-code** [comment]
**Update**:

v0.9.4 works for me

**Comment by Dankr4d** [comment]
This error will also show up if the BF2142Patched.exe is running or opened by another process. `no write permissions` could be misleading at this point.
Could you check if the BF2142Patched.exe process is running and kill it, if it is? Maybe this will solve the issue.

**Comment by pot-code** [comment]
@Dankr4d No :), I did a reboot and ran BF2142Unlocker.exe directly, nothing changes.

**Comment by Dankr4d** [comment]
Hmm, this is strange since I didn't modify the logic how write permission is checked.
Can you delete the BF2142Patched.exe and retry?

**Comment by pot-code** [comment]
@Dankr4d Holy...It works now, but I had moved it out of the installation folder, and it didn't work. Meh, confused af.

Anyway, thank you for your help :)

**Comment by Dankr4d** [comment]
Thank you. Would be interesting to know what exactly happened, I've currently no idea.
